FROM node:20-slim

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable
COPY . /app
WORKDIR /app

#RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --prod --frozen-lockfile
RUN pnpm install
RUN pnpm i -g serve

EXPOSE 3000

CMD [ "npx", "nuxi" "generate" ]
CMD [ "npx", "serve", ".output/public"]
