# This is a basic workflow to help you get started with Actions
name: build docker image
# Controls when the action will run.
on:
  push:
    branches:
      - dev

jobs:
  build-image:
    name: Build Images
    environment: development
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to the DockerHub Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          logout: false

      - name: Build And Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.dev
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ftlikon/each_star_frontend_dev:${{ env.GITHUB_SHA }}
            ftlikon/each_star_frontend_dev:latest

  deploy-image-to-server:
    name: Deploy Images To Server
    environment: development
    needs: build-image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Deploy to Remote Server
        uses: garygrossgarten/github-action-ssh@release
        with:
          host: ${{ secrets.DEPLOY_SERVER }}
          username: ubuntu
          password: ${{ secrets.SERVER_PASSWORD }}
          command: |
            sudo docker ps -a | sudo grep "each_star_frontend_dev" | sudo awk '{print $1}' | sudo xargs docker rm -f
            sudo docker images | sudo grep "each_star_frontend_dev" | sudo awk '{print $3}' | sudo xargs docker rmi -f
            sudo docker pull ftlikon/each_star_frontend_dev:${{ env.GITHUB_SHA }} && sudo docker run -d -p 2998:3000 ftlikon/each_star_frontend_dev:${{ env.GITHUB_SHA }}

